version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - .:/nextjs-dashboard
    restart: always
    ports:
      - 5000:3000
    command: npm run dev
